### ISSUE TITLE
clang-format如何配置

### ISSUE THREAD

**Issue by tbago** [VisualGMQ/my-nvim-config#1]
我想配置下clang-format在nvim中实现自动格式化代码。我看到配置文件中有format.lua。但是没有调用，这个具体应该如何实现呢。
我本身已经通过homebrew安装了clang-format。

**Comment by VisualGMQ** [comment]
那个是我自己写的函数，不是很建议调用。你可以看看插件
https://github.com/mhartington/formatter.nvim

**Comment by tbago** [comment]
好的，谢谢，我主要是用clang-format来格式化代码。我知道怎么处理了。

**Comment by tbago** [comment]
好的，谢谢，我主要是用clang-format来格式化代码。我知道怎么处理了。
